### PR TITLE
errors: explain `SYS_ASSERTION_FAILED` exit code in more detail.

### PR DESCRIPTION
**Pull request by raulk**
Adds the exit code to handle https://github.com/filecoin-project/ref-fvm/issues/508.

### CODE REVIEW

**Comment by Stebalien** [comment]
The plan was to use `SYS_ASSERTION_FAILED` for this, but I'm happy to rename it (the current name mirrors `USR_ASSERTION_FAILED`.

**Comment by raulk** [comment]
@Stebalien That's what I thought, but I'm not entirely sure of what is happening here, because this code is already in use in non-fatal errors:

https://github.com/filecoin-project/ref-fvm/blob/master/fvm/src/executor/default.rs#L122-L130

Generally speaking, I'm having a hard time understanding why the Executor (the outermost component in the FVM design) is _handling_ syscall errors. This seems like some abstraction leakage, because syscalls only exist _inside_ invocation containers.

That leakage also seems to be present [here](https://github.com/filecoin-project/ref-fvm/blob/391a3fab802f3770cdef5c300c8ba2c212ca50f8/fvm/src/machine/default.rs#L192): a non-syscall method emitting syscall errors?

Maybe Syscall Errors are not just constrained to Syscalls, they are just "named" errors, as opposed unnamed errors, i.e. fatal errors?

**Comment by raulk** [comment]
Agree that that design would allow us to enumerate every error that a syscall can throw explicitly, and this translates to better safety. It does become extremely verbose though. At the end of the day, we are interested in:

1. Allowing actors to handle syscall errors.
2. Providing default exit codes for those errors in case the actor that first witnessed the error does not want to handle it.

I wonder if there are simpler designs that would hit that ultimate motivation better.

---

@Stebalien Now that things are clearer re: `SYS_ASSERTION_FAILED`, I've reverted the introduction of the new exit code, and updated this PR to specify exactly when it's used. Please take a look.

**Review by Stebalien — APPROVED** [review]

**Comment by Stebalien** [comment]
> I wonder if there are simpler designs that would hit that ultimate motivation better.

We could probably add custom error types _just_ for send & transfer. Or we could add a helper method for the top-level send?

**Pull request merged**
